# Generated by Django 5.0.3 on 2024-04-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("icon", models.ImageField(upload_to="photos/%Y/%m/%d/")),
            ],
        ),
    ]
