# Generated by Django 5.0.3 on 2024-04-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_chef_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("banner_photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
            ],
        ),
    ]
