# Generated by Django 5.0.3 on 2024-04-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_locale"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Locale",
        ),
    ]
