# Generated by Django 5.0.3 on 2024-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dessert",
            name="dessert_photo_2",
            field=models.ImageField(
                default="media/photos/2024/04/01/default.jpg",
                upload_to="photos/%Y/%m/%d/",
            ),
        ),
    ]
