# Generated by Django 5.0.3 on 2024-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0004_alter_dessert_locale_name_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dessert",
            name="featured_ingredient_photo_2",
            field=models.ImageField(
                default="media/photos/2024/04/01/default.jpg",
                upload_to="photos/%Y/%m/%d/",
            ),
        ),
    ]
