# Generated by Django 5.0.3 on 2024-04-16 19:00

import desserts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0009_alter_dessert_locale_name_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="dessert",
            name="additional_ingredient",
            field=desserts.models.MultiSelectField(
                choices=[
                    ("coconut", "coconut"),
                    ("cinnamon", "cinnamon"),
                    ("mascarpone", "mascarpone"),
                    ("lucuma", "lucuma"),
                    ("matcha", "matcha"),
                    ("apple", "apple"),
                    ("sweetened condensed milk", "sweetened condensed milk"),
                    ("dulce de leche", "dulce de leche"),
                    ("plantain", "plantain"),
                    ("chocolate", "chocolate"),
                    ("whiskey", "whiskey"),
                    ("egg yolk", "egg yolk"),
                    ("oat", "oat"),
                    ("taro", "taro"),
                    ("kiwifruit", "kiwifruit"),
                    ("milk", "milk"),
                    ("paneer", "paneer"),
                    ("cottage cheese", "cottage cheese"),
                    ("honey", "honey"),
                    ("custard", "custard"),
                    ("filo pastry", "filo pastry"),
                    ("peanuts", "peanuts"),
                    ("dates", "dates"),
                    ("almond", "almond"),
                    ("maple syrup", "maple syrup"),
                    ("red bean paste", "red bean paste"),
                    ("quinoa", "quinoa"),
                    ("sugarcane", "sugarcane"),
                    ("rum", "rum"),
                    ("vanilla", "vanilla"),
                    ("tropical fruit", "tropical fruit"),
                    ("cassava", "cassava"),
                    ("rosewater", "rosewater"),
                    ("dulce de parchita", "dulce de parchita"),
                    ("palm sugar", "palm sugar"),
                    ("berries", "berries"),
                    ("walnut", "walnut"),
                    ("corn", "corn"),
                    ("pistachio", "pistachio"),
                    ("rice", "rice"),
                    ("cocoa-powder", "cocoa-powder"),
                    ("cardamom", "cardamom"),
                    ("hazelnut", "hazelnut"),
                    ("apple", "apple"),
                    ("egg whites", "egg whites"),
                    ("puff pastry", "puff pastry"),
                    ("tvorog", "tovrog"),
                    ("flour", "flour"),
                    ("ube", "ube"),
                    ("pasta", "pasta"),
                    ("anise", "anise"),
                    ("none", "none"),
                ],
                null=True,
            ),
        ),
    ]
