# Generated by Django 5.0.3 on 2024-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0017_category_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dessert",
            name="category",
        ),
        migrations.RemoveField(
            model_name="dessert",
            name="category_add",
        ),
        migrations.RemoveField(
            model_name="dessert",
            name="locale_name_add",
        ),
        migrations.AddField(
            model_name="dessert",
            name="categories",
            field=models.ManyToManyField(to="desserts.category"),
        ),
        migrations.RemoveField(
            model_name="dessert",
            name="locale_name",
        ),
        migrations.AddField(
            model_name="dessert",
            name="locale_name",
            field=models.ManyToManyField(to="desserts.locale"),
        ),
    ]
