# Generated by Django 5.0.3 on 2024-04-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0019_rename_categories_dessert_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="locale",
            name="banner_photo",
            field=models.ImageField(
                default="media/photos/2024/04/01/default.jpg",
                upload_to="photos/%Y/%m/%d/",
            ),
        ),
    ]
