# Generated by Django 5.0.3 on 2024-04-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0020_locale_banner_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="dessert",
            name="additional_ingredient",
        ),
        migrations.AddField(
            model_name="dessert",
            name="additional_ingredient",
            field=models.ManyToManyField(to="desserts.ingredient"),
        ),
    ]
