# Generated by Django 5.0.3 on 2024-04-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0021_ingredient_remove_dessert_additional_ingredient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dessert",
            name="additional_ingredient",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="photo",
            field=models.ImageField(
                default="media/photos/2024/04/01/default.jpg",
                upload_to="photos/%Y/%m/%d/",
            ),
        ),
        migrations.RemoveField(
            model_name="dessert",
            name="featured_ingredient",
        ),
        migrations.AddField(
            model_name="dessert",
            name="featured_ingredient",
            field=models.ManyToManyField(to="desserts.ingredient"),
        ),
    ]
