# Generated by Django 5.0.3 on 2024-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0022_remove_dessert_additional_ingredient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dessert",
            name="category",
        ),
        migrations.AddField(
            model_name="dessert",
            name="category",
            field=models.CharField(
                choices=[
                    ("Cakes", "Cakes"),
                    ("Pies & Tarts", "Pies & Tarts"),
                    ("Cookies & Bars", "Cookies & Bars"),
                    ("Pastries", "Pastries"),
                    ("Puddings & Custards", "Puddings & Custards"),
                    ("Frozen Desserts", "Frozen Desserts"),
                    ("Confections & Candies", "Confections & Candies"),
                    ("Fruit Desserts", "Fruit Desserts"),
                    ("Fried Dough", "Fried Dough"),
                ],
                default=False,
                max_length=100,
            ),
        ),
    ]
