# Generated by Django 5.0.3 on 2024-04-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0023_remove_dessert_category_dessert_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dessert",
            old_name="featured_ingredient_photo_2",
            new_name="dessert_photo_3",
        ),
        migrations.RemoveField(
            model_name="dessert",
            name="featured_ingredient_photo",
        ),
        migrations.AddField(
            model_name="dessert",
            name="dessert_photo_4",
            field=models.ImageField(
                default="media/photos/2024/04/01/default.jpg",
                upload_to="photos/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="dessert",
            name="featured_ingredient",
            field=models.ManyToManyField(
                related_name="desserts", to="desserts.ingredient"
            ),
        ),
    ]
