# Generated by Django 5.0.3 on 2024-04-18 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "desserts",
            "0024_rename_featured_ingredient_photo_2_dessert_dessert_photo_3_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DessertVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("preparation_method", models.TextField(blank=True, max_length=800)),
                (
                    "dessert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="desserts.dessert",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dessert_variations",
                        to="desserts.locale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("preparation_method", models.TextField(blank=True, max_length=800)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="desserts.ingredient",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_variations",
                        to="desserts.locale",
                    ),
                ),
            ],
        ),
    ]
