# Generated by Django 5.0.3 on 2024-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0025_dessertvariation_ingredientvariation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dessertvariation",
            name="dessert_photo",
            field=models.ImageField(
                default="media/photos/2024/04/01/default.jpg",
                upload_to="photos/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="dessertvariation",
            name="dessert_photo_2",
            field=models.ImageField(
                default="media/photos/2024/04/01/default.jpg",
                upload_to="photos/%Y/%m/%d/",
            ),
        ),
    ]
